tokenizer:
  path: /workspace/cs336-assignment1-basics/data/tokenizer_TinyStories_10k

model:
  vocab_size: 10000
  context_length: 256
  num_layers: 2
  d_model: 512
  num_heads: 16
  d_ff: 1344
  theta: 10000 # rope_theta
  load_checkpoint_path: /workspace/cs336-assignment1-basics/data/checkpoint/tinystories-train/final_20251213_0846/iter_10000.bin

generation:
  max_new_tokens: 1000
  temperature: 1.0
  top_p: 0.5
  eos_token: "<|endoftext|>"