data:
  train_batch_size: 128
  val_batch_size: 128
  train_file: /workspace/cs336-assignment1-basics/data/data_bin/owt_train.bin
  val_file: /workspace/cs336-assignment1-basics/data/data_bin/owt_valid.bin

tokenizer:
  path: /workspace/cs336-assignment1-basics/data/tokenizer_owt_32k_optim

model:
  vocab_size: 32000
  context_length: 256
  num_layers: 4
  d_model: 512
  num_heads: 16
  d_ff: 1344
  theta: 10000 # rope_theta

optim:
  lr: 3.0e-4
  min_lr: 3.0e-5
  warmup_ratio: 0.1
  weight_decay: 0.01
  betas:
    - 0.9
    - 0.999
  gradient_clipping: true
  clip: 1.0


trainer:
  total_steps: 10000
  project_name: owt-train
  experiment_name: final
  val_before_train: true
  val_freq: 50
  save_checkpoint_path: /workspace/cs336-assignment1-basics/data/checkpoint
  save_freq: 5000
  save_model_only: true

debug:
  debug_mode: false
  log_data_sample: true